// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionsList: typeof import('./src/components/actionlist/ActionsList.vue')['default']
    AutoComplete: typeof import('./src/components/field/AutoComplete.vue')['default']
    AutoCompleteMulti: typeof import('./src/components/field/AutoCompleteMulti.vue')['default']
    AutoCompleteRemote: typeof import('./src/components/field/AutoCompleteRemote.vue')['default']
    Base: typeof import('./src/components/field/Base.vue')['default']
    BaseItem: typeof import('./src/components/list/BaseItem.vue')['default']
    Basic: typeof import('./src/components/overlay/Basic.vue')['default']
    Currency: typeof import('./src/components/field/Currency.vue')['default']
    Date: typeof import('./src/components/field/Date.vue')['default']
    DateTime: typeof import('./src/components/field/DateTime.vue')['default']
    Delete: typeof import('./src/components/modal/Delete.vue')['default']
    EMail: typeof import('./src/components/field/EMail.vue')['default']
    Header: typeof import('./src/components/breadcrumbs/Header.vue')['default']
    Html: typeof import('./src/components/field/Html.vue')['default']
    LoadingItem: typeof import('./src/components/list/LoadingItem.vue')['default']
    Main: typeof import('./src/components/base/list/Main.vue')['default']
    MultiSelect: typeof import('./src/components/field/MultiSelect.vue')['default']
    Number: typeof import('./src/components/field/Number.vue')['default']
    NutriBar: typeof import('./src/components/score/NutriBar.vue')['default']
    NutriSlim: typeof import('./src/components/score/NutriSlim.vue')['default']
    PageWrapper: typeof import('./src/components/base/PageWrapper.vue')['default']
    Password: typeof import('./src/components/field/Password.vue')['default']
    PhoneNumber: typeof import('./src/components/field/PhoneNumber.vue')['default']
    Primary: typeof import('./src/components/button/Primary.vue')['default']
    Radio: typeof import('./src/components/field/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Secondary: typeof import('./src/components/button/Secondary.vue')['default']
    Select: typeof import('./src/components/field/Select.vue')['default']
    Simple: typeof import('./src/components/avatar/Simple.vue')['default']
    SimpleList: typeof import('./src/components/list/SimpleList.vue')['default']
    SmallList: typeof import('./src/components/list/SmallList.vue')['default']
    StepFrame: typeof import('./src/components/stepper/StepFrame.vue')['default']
    StepperNav: typeof import('./src/components/stepper/StepperNav.vue')['default']
    StepperNavSmall: typeof import('./src/components/stepper/StepperNavSmall.vue')['default']
    TabGroup: typeof import('./src/components/menu/TabGroup.vue')['default']
    TabGroupBig: typeof import('./src/components/menu/TabGroupBig.vue')['default']
    TabWrapper: typeof import('./src/components/base/TabWrapper.vue')['default']
    Text: typeof import('./src/components/field/Text.vue')['default']
    TextArea: typeof import('./src/components/field/TextArea.vue')['default']
    Toggle: typeof import('./src/components/field/Toggle.vue')['default']
    ToolDropdown: typeof import('./src/components/base/list/components/ToolDropdown.vue')['default']
    ZIP: typeof import('./src/components/field/ZIP.vue')['default']
  }
}

export { }
